apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-one
  template:
    metadata:
      labels:
        app: project-one
    spec:
      containers:
        - name: project-one
          image: manly111/project-one:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"