apiVersion: v1
kind: Service
metadata:
  name: project-one-svc
  labels:
    app: project-one
spec:
  type: NodePort
  selector:
    app: project-one
  ports:
    - name: http
      port: 3000
      targetPort: 3000